#!/bin/bash
# Makes a tarball release

ver=$(grep "const char.*Version" espeakup.c)
ver=${ver%\"*}
ver=${ver#*\"}

PREFIX=espeakup-${ver}
REL=${1:-v${ver}}

TIMESTAMP=
if [ "$REL" != "v${ver}" ]; then
	TIMESTAMP="_p`date +%Y%m%d`"
fi

TARFILE=${PREFIX}${TIMESTAMP}.tar

git archive --format=tar --prefix=${PREFIX}/ $REL > ${TARFILE}
tar f ${TARFILE} --delete ${PREFIX}/.gitignore --delete ${PREFIX}/makedist
bzip2 ${TARFILE}
echo Produced ${TARFILE}*
