#!/bin/bash
# Makes a tarball release

VER=$(./version)
PREFIX=espeakup-${VER}
REL=${1:-v${VER}}

if [ "$REL" != "v${VER}" ]; then
	TIMESTAMP=`git show $REL --pretty=format:%ai |head -1`
	PATCHLEVEL=`date --utc -d "$TIMESTAMP" +_p%Y%m%d%H%M`
fi

TARFILE=${PREFIX}${PATCHLEVEL}.tar

git archive --format=tar --prefix=${PREFIX}/ $REL > ${TARFILE}
tar f ${TARFILE} --delete ${PREFIX}/.gitignore --delete ${PREFIX}/tarball
bzip2 ${TARFILE}
echo "Produced ${TARFILE}.bz2"
